version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout

      - run:
          name: Install dependencies
          working_directory: /
          command: sudo apt-get -y -qq install awscli

      - run:
          name: Deploy application
          command: aws s3 cp mike-s-test.html s3://iwc-ci-demo
